version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5400:5432
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis_db:
    container_name: redis_db
    image: redis:7.2.6
    restart: always
    ports:
      - 6000:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
     - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: